destination: /var/www/blog
permalink: /:title
title: Serious Technobabble
email: istepaniuk@gmail.com
description: Iván Stepaniuk's blog about software craftsmanship
baseurl: ""
url: "http://blog.istepaniuk.com"
twitter_username: istepaniuk
github_username:  istepaniuk
exclude:
  - Gruntfile.js
  - LICENSE
  - node_modules/
  - README.md

markdown: redcarpet
redcarpet:
  extensions: ["tables"]
highlighter: pygments

google_analytics_id: "UA-30612993-1"

paginate: 5
paginate_path: "page/:num/"

noita:
  name: Serious Technobabble
  description: Iván Stepaniuk's blog about software craftsmanship
  author:
    name: Iván Stepaniuk
    url: http://github.com/istepaniuk
  lang: en
  topbar:
    toggle: Menu
    right:
      - name: About
        url: /about/
      - name: Book List
        url: /book-list/
      - name: Talks & Events
        url: /talks-events/
      - name: Repository
        url: https://github.com/istepaniuk/istepaniuk-com
        class: small button

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      is_post: true
