destination: /var/www/blog
permalink: /:title
title: Serious Technobabble
email: istepaniuk@gmail.com
description: >
  Iván Stepaniuk's blog about software craftsmanship
baseurl: ""
url: "http://blog2.istepaniuk.com"
twitter_username: istepaniuk
github_username:  istepaniuk

markdown: redcarpet
highlighter: pygments
