gems: [jekyll-paginate]

destination: /var/www/blog
permalink: /:title
title: Serious Technobabble
email: istepaniuk@__remove__this__gmail.com
description: Iván Stepaniuk's blog about software craftsmanship
baseurl: ""
url: "https://blog.istepaniuk.com"
twitter_username: istepaniuk
github_username:  istepaniuk
exclude:
  - Gruntfile.js
  - LICENSE
  - node_modules/
  - README.md

markdown: redcarpet
redcarpet:
  extensions: ["tables", "fenced_code_blocks"]

highlighter: pygments

paginate: 5
paginate_path: "page/:num/"

sass:
    sass_dir: _sass
    style: :compressed

noita:
  name: Serious Technobabble
  description: Iván Stepaniuk's blog about software craftsmanship
  author:
    name: Iván Stepaniuk
    url: http://github.com/istepaniuk
  lang: en
  topbar:
    toggle: Menu
    right:
      - name: About
        url: /about/
      - name: Book List
        url: /book-list/
      - name: Repository
        url: https://github.com/istepaniuk/istepaniuk-com
        class: small button

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      is_post: true
