name: Jekyll site CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll \
        -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:4.1.0 /bin/bash -c \
        "chmod 777 /srv/jekyll && git submodule init && git submodule update && jekyll build --future && apk add tidyhtml && find _site -name \"*.html\" -exec tidy -config _tidy_config.txt {} \\;"


    # Copying files and artifacts via SSH
    - name: Copying files to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
        rm: true
        source: "${{ github.workspace }}/_site"
        target: "${{ secrets.REMOTE_DIR }}"
        strip_components: 3
